### ISSUE TITLE
Last publish failed due to jsdoc error

### ISSUE THREAD

**Issue by L2jLiga** [amzn/sketch-constructor#113]
from https://travis-ci.org/github/amzn/sketch-constructor/jobs/688221385

```
> node ./scripts/generateDocs.js
/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-api/lib/jsdoc-command.js:114
      throw err
      ^
JSDOC_ERROR: [
    at ExplainSync.verifyOutput (/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-api/lib/jsdoc-command.js:112:19)
    at ExplainSync._runJsdoc (/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-api/lib/explain-sync.js:31:32)
    at ExplainSync.getOutput (/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-api/lib/explain-sync.js:12:21)
    at ExplainSync.execute (/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-api/lib/jsdoc-command.js:49:24)
    at Object.explainSync (/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-api/index.js:29:18)
    at JsdocToMarkdown.getJsdocDataSync (/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-to-markdown/index.js:131:21)
    at JsdocToMarkdown.getTemplateDataSync (/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-to-markdown/index.js:101:28)
    at JsdocToMarkdown.renderSync (/home/travis/build/amzn/sketch-constructor/node_modules/jsdoc-to-markdown/index.js:72:23)
    at Object.<anonymous> (/home/travis/build/amzn/sketch-constructor/scripts/generateDocs.js:6:25)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sketch-constructor@0.0.0-development docs:build: `node ./scripts/generateDocs.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sketch-constructor@0.0.0-development docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-05-18T04_11_23_135Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sketch-constructor@1.21.0 preversion: `npm test && npm run docs:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sketch-constructor@1.21.0 preversion script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-05-18T04_11_23_162Z-debug.log
[4:11:23 AM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
```

**Comment by dbanksdesign** [comment]
I have 0 idea how to fix this

**Comment by L2jLiga** [comment]
Created issues in jsdoc-api: https://github.com/jsdoc2md/jsdoc-api/issues/21

**Comment by L2jLiga** [comment]
Also fix is on the way
